### ISSUE TITLE
Landmark Prediction Stage(stage1)

### ISSUE THREAD

**Issue by UdonDa** [YaN9-Y/lafin#3]
Hi @YaN9-Y.
Thank you for providing your codes.

I have two questions about the training of stage 1.

Firstly,
According to the TRAIN_LANDMARK_LANDMARK_FLIST in `config.yml.example`, the value should be set to `wflw_train_landmarks`, ok.

However, in this setting, because the wflw landmark has the 196 points, should we set LANDMARK_POINTS to 98?
The default value is set to 68 and you write the 68 in the paper.

Secondly,
When we want to use the default value of 68, which landmark dataset should we use?

Thanks.

**Comment by YaN9-Y** [comment]
Hello Udonda,
WFLW is a dataset for landmark detection task. We adopt this dataset to investigate whether the inpainting augmentation can help boosting the landmark prediction performance. If you want to hold experiments on WFLW dataset, the LANDMARK_POINTS should be set to 98. 
Otherwise, if you want to hold experiment on image inpainting, use celeba-hq dataset. The 68 points ground truth landmarks can be generated following steps in readme.

**Comment by UdonDa** [comment]
Thank you for replying.

So, if I use a celeba dataset, we set TRAIN_LANDMARK_LANDMARK_FLIST to `celeba_train_landmarks.flist` following this step(https://github.com/YaN9-Y/lafin#2-landmarks), right?

**Comment by YaN9-Y** [comment]
Right.

**Comment by UdonDa** [comment]
Thank you!
